# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138ejFFG2zm-F6trVxI107x9NKnPq6n2k
"""

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

# Step 1: Load CSV file into a pandas DataFrame
data = pd.read_csv('/content/salaries.csv')

# Assuming your CSV file has columns named 'x' and 'y'
x = data['salary']
y = data['salary_in_usd']

# Split the data into training and testing sets
train_x = x[:80]
train_y = y[:80]
test_x = x[80:]
test_y = y[80:]

# Train the model
mymodel = np.poly1d(np.polyfit(train_x, train_y, 4))

# Calculate R^2 score on the training data
r2 = r2_score(train_y, mymodel(train_x))

# Plot the scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(train_x, train_y, color='blue', label='Actual data')
plt.plot(train_x, mymodel(train_x), color='red', label='Polynomial fit')
plt.title('Scatter plot with Polynomial fit (Training data)')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()

print("R^2 score:", r2)